'use client'

import CustomThemeProvider from '@/context/themeContext'
import { GlobalStyle } from '@/styles/GlobalStyles'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TMDB App',
  description: 'Generated by Paulo Turino',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <CustomThemeProvider>
        <GlobalStyle />
        <body className={inter.className}>{children}</body>
      </CustomThemeProvider>
    </html>
  )
}
